# =============================================================================
# Config: configs/default.yaml  –  base hyper-parameters
# -----------------------------------------------------------------------------
# latent_dim    : 4
# image_size    : [128, 640]
# beta_schedule : linear
# lr            : 1e-4
# ema_decay     : 0.9999
# sampler       : ddim
# steps         : 1000
# =============================================================================
