# =============================================================================
# Config: configs/infer.yaml  –  inference parameters
# -----------------------------------------------------------------------------
# checkpoint_path : checkpoints/best.ckpt
# sampler         : dpm_solver
# steps           : 50
# cfg_scale       : 3.0
# output_wav      : generated.wav
# =============================================================================
