data:
  # path: "/content/drive/MyDrive/College/Tsinghua/Multi-modal_Machine_Learning/MMML_Project/data/processed"
  path: "/content/drive/MyDrive/MMML_Project/data/processed"
  batch_size: 64
  num_workers: 4