# =============================================================================
# Config: configs/train.yaml  –  training overrides
# -----------------------------------------------------------------------------
# batch_size : 8
# epochs     : 250
# guidance:
#   classifier_free : 0.10
#   double_guidance : true
# ckpt_every_n_steps : 5000
# =============================================================================
