data:
  path: "/content/drive/MyDrive/College/Tsinghua/Multi-modal_Machine_Learning/MMML_Project/data/raw/vggsound"
  # path: "/content/drive/MyDrive/MMML_Project/data/raw/vggsound"
  batch_size: 12
  num_workers: 1
model:
  feat_dim: 512
loss:
  clip_num: 2
  temperature: 0.07
  lambda_: 1.0
optim:
  lr: 8e-4
  weight_decay: 1e-4
training:
  ckpt_dir: "/content/drive/MyDrive/College/Tsinghua/Multi-modal_Machine_Learning/MMML_Project/checkpoints/cavp"
  total_steps: 10_000
  clip_grad_norm: 1.0
  ckpt_every: 10
